### ISSUE TITLE
linux环境部署读取不到holiday下json文件

### ISSUE THREAD

**Issue by ghggSky** [YangShuqing/holiday#1]
![image](https://user-images.githubusercontent.com/37231325/195258869-64e34959-2ba0-430f-ab8d-397609960e4f.png)

**Comment by YangShuqing** [comment]
使用版本 0.0.5-2022试下

**Comment by ghggSky** [comment]
大神，咱们什么时候更显2023的节假日，如果更新了2023节假日json，代码有变化吗？

**Comment by YangShuqing** [comment]
> 大神，咱们什么时候更显2023的节假日，如果更新了2023节假日json，代码有变化吗？

已更新 2023和2024 节假日 ，无变化
